service: nx-sls
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'test'}
  region: us-east-2

functions:
  sls-nest:
    handler: dist/apps/sls-nest/main.handler
    events:
      - http:
          method: any
          path: /{any+}
          cors: true

package:
  individually: true

plugins:
  - serverless-plugin-optimize
